SELECT count(*) from t1;
SELECT sum(v1) from t1;
SELECT avg(v1) from t1;
SELECT count(*) from ts2;
SELECT sum(v1) from ts2;
SELECT avg(v1) from ts2;
SELECT count(*) from ts3;
SELECT sum(v1) from ts3;
SELECT avg(v1) from ts3;